
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.servidormusica.analizadores;

/** CUP generated class containing symbol constants. */
public class symLista {
  /* terminals */
  public static final int COMA = 7;
  public static final int RANDOM = 11;
  public static final int FALSO = 8;
  public static final int CONT_CADENA = 15;
  public static final int CORCHETC = 5;
  public static final int LISTA = 10;
  public static final int DOPUNTO = 6;
  public static final int CORCHETA = 4;
  public static final int EOF = 0;
  public static final int LLAVEC = 3;
  public static final int ID = 14;
  public static final int PISTAS = 13;
  public static final int error = 1;
  public static final int LLAVEA = 2;
  public static final int VERDADERO = 16;
  public static final int NOMBRE = 9;
  public static final int CIRCULAR = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LLAVEA",
  "LLAVEC",
  "CORCHETA",
  "CORCHETC",
  "DOPUNTO",
  "COMA",
  "FALSO",
  "NOMBRE",
  "LISTA",
  "RANDOM",
  "CIRCULAR",
  "PISTAS",
  "ID",
  "CONT_CADENA",
  "VERDADERO"
  };
}

