
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.servidormusica.analizadores;

/** CUP generated class containing symbol constants. */
public class symPista {
  /* terminals */
  public static final int CONT_CARACTER = 12;
  public static final int DIVISION = 19;
  public static final int CORCHETC = 59;
  public static final int CORCHETA = 58;
  public static final int CONTINUAR = 65;
  public static final int NOTA_DO_S = 70;
  public static final int POTENCIA = 21;
  public static final int MENSAJE = 62;
  public static final int VERDADERO = 15;
  public static final int SI = 48;
  public static final int KEEP = 36;
  public static final int PRIMOS = 84;
  public static final int INCREMENT = 46;
  public static final int FALSO = 14;
  public static final int POR = 18;
  public static final int PISTA = 2;
  public static final int SUMA_IMPLICITA = 45;
  public static final int LONGITUD = 64;
  public static final int NOT = 44;
  public static final int NOR = 41;
  public static final int ORDENAR = 63;
  public static final int VAR = 35;
  public static final int NOTEQUALS = 26;
  public static final int ISNULO = 37;
  public static final int IMPARES = 83;
  public static final int SALIR = 52;
  public static final int HACER = 56;
  public static final int NOTA_MI = 73;
  public static final int PARA = 55;
  public static final int NUM_ENTERO = 10;
  public static final int PARES = 82;
  public static final int COMA = 7;
  public static final int ENTERO = 28;
  public static final int MODULO = 20;
  public static final int DOBLE = 29;
  public static final int IGUAL = 33;
  public static final int DECIMAL = 11;
  public static final int BOOLEAN = 30;
  public static final int SWITCH = 51;
  public static final int NOTA_FA_S = 75;
  public static final int NOTA_FA = 74;
  public static final int MENOS = 17;
  public static final int MAS = 16;
  public static final int NOTA_LA = 78;
  public static final int NOTA_RE = 71;
  public static final int ARREGLO = 60;
  public static final int EOF = 0;
  public static final int MIENTRAS = 38;
  public static final int MENOROI = 25;
  public static final int DEFAULT = 54;
  public static final int DECREMENT = 47;
  public static final int SUMARIZAR = 67;
  public static final int CARACTER = 32;
  public static final int NOTA_LA_S = 79;
  public static final int PRINCIPAL = 66;
  public static final int OR = 39;
  public static final int error = 1;
  public static final int REPRODUCIR = 68;
  public static final int NOTA_RE_S = 72;
  public static final int NOTA_SOL = 76;
  public static final int ID = 3;
  public static final int MENORQ = 23;
  public static final int SINO = 49;
  public static final int DOPUNTO = 50;
  public static final int EXTIENDE = 4;
  public static final int CASO = 53;
  public static final int NOTA_DO = 69;
  public static final int ESPERAR = 61;
  public static final int MAYORQ = 22;
  public static final int PARENTESISC = 9;
  public static final int RETORNA = 57;
  public static final int PARENTESISA = 8;
  public static final int PUNTOCOMA = 34;
  public static final int CONT_CADENA = 13;
  public static final int CADENA = 31;
  public static final int NOTA_SOL_S = 77;
  public static final int ASCENDENTE = 80;
  public static final int AND = 42;
  public static final int LLAVEC = 6;
  public static final int LLAVEA = 5;
  public static final int MAYOROI = 24;
  public static final int DESCENDENTE = 81;
  public static final int NAND = 43;
  public static final int XOR = 40;
  public static final int EQUALS = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PISTA",
  "ID",
  "EXTIENDE",
  "LLAVEA",
  "LLAVEC",
  "COMA",
  "PARENTESISA",
  "PARENTESISC",
  "NUM_ENTERO",
  "DECIMAL",
  "CONT_CARACTER",
  "CONT_CADENA",
  "FALSO",
  "VERDADERO",
  "MAS",
  "MENOS",
  "POR",
  "DIVISION",
  "MODULO",
  "POTENCIA",
  "MAYORQ",
  "MENORQ",
  "MAYOROI",
  "MENOROI",
  "NOTEQUALS",
  "EQUALS",
  "ENTERO",
  "DOBLE",
  "BOOLEAN",
  "CADENA",
  "CARACTER",
  "IGUAL",
  "PUNTOCOMA",
  "VAR",
  "KEEP",
  "ISNULO",
  "MIENTRAS",
  "OR",
  "XOR",
  "NOR",
  "AND",
  "NAND",
  "NOT",
  "SUMA_IMPLICITA",
  "INCREMENT",
  "DECREMENT",
  "SI",
  "SINO",
  "DOPUNTO",
  "SWITCH",
  "SALIR",
  "CASO",
  "DEFAULT",
  "PARA",
  "HACER",
  "RETORNA",
  "CORCHETA",
  "CORCHETC",
  "ARREGLO",
  "ESPERAR",
  "MENSAJE",
  "ORDENAR",
  "LONGITUD",
  "CONTINUAR",
  "PRINCIPAL",
  "SUMARIZAR",
  "REPRODUCIR",
  "NOTA_DO",
  "NOTA_DO_S",
  "NOTA_RE",
  "NOTA_RE_S",
  "NOTA_MI",
  "NOTA_FA",
  "NOTA_FA_S",
  "NOTA_SOL",
  "NOTA_SOL_S",
  "NOTA_LA",
  "NOTA_LA_S",
  "ASCENDENTE",
  "DESCENDENTE",
  "PARES",
  "IMPARES",
  "PRIMOS"
  };
}

